#!/bin/sh
# create hash links on all files in the specified directory

_print=
_v=

case $1 in
    -v ) _print=-print _v=-v
         shift ;;
esac

case $# in
    0 ) set /etc/pki/tls/certs ;;
esac

cd "$1" || exit $?


if type update-ca-trust > /dev/null 2>&1 ; then
    test -n "$_print" && echo "* running update-ca-trust"
    update-ca-trust
else
    test -n "$_print" && echo "* Removing existing hash symlinks"
    find * -name '????????.[0-9]*' -type l $_print -delete
fi

test -n "$_print" && echo "* Installing local hash symlinks"
for file in * ; do
    if [ -f "$file" ] && ! [ -L "$file" ]; then
        hash=$(openssl x509 -hash -noout -in "$file" 2>/dev/null)
        test -z "$hash" && continue
        suffix=0
        while [ -e "$hash.$suffix" ] ; do
    	    suffix=$(($suffix + 1))
        done
        ln $_v -sf "$file" "$hash.$suffix"
    fi
done
