#! /bin/sh
# $Id$

# For the moment, I want an error if I don't use gnu cpio.

#if cpio --version < /dev/null > /dev/null 2>&1 ; then
  exec cpio -dimv --no-absolute-filenames ${1+"$@"}
#else
#  exec cpio -dimv ${1+"$@"}
#fi
