#!/bin/sh
# $Id: ctof,v 1.1 2019/02/07 23:12:23 friedman Exp $

case $# in
    0 ) read temp
        set : $temp
        shift ;;
esac

for temp in "$@"; do
    units -1t "tempC($temp)" tempF
done

# eof
