#! /bin/sh
# $Id: cvs-gnu,v 1.3 2000/04/10 09:12:02 friedman Exp $

# Old repository
#CVSROOT=:pserver:friedman@cvs.gnu.org:/gd/gnu/cvsroot

# See also http://www.gnu.org/software/devel.html#CVS
CVSROOT=:pserver:anoncvs@subversions.gnu.org:/home/cvs
export CVSROOT

exec ${CVS-cvs} ${1+"$@"}
