#! /bin/sh
# $Id: cvs-gila,v 1.2 1998/04/14 00:46:09 friedman Exp $

CVSROOT=:pserver:friedman%netscape.com@gila.mozilla.org:/cvsroot
export CVSROOT

CVS_RSH=ssh
export CVS_RSH

exec ${CVS-cvs} ${1+"$@"}
