#!/bin/sh
# cyrus-deliver --- wrapper for procmail to deliver to cyrus imap server
# Author: Noah Friedman <friedman@splode.com>
# Created: 2005-05-12
# Public domain

# $Id: cyrus-deliver,v 1.1 2005/05/12 19:51:29 friedman Exp $

# Commentary:

# The cyrus delivery agent requires access to a unix-domain socket which is
# only accessible to group `mail'.  If the restricted delivery wrapper is
# installed and is setgid, then use that.  Otherwise, try to use deliver
# directly.  If that STILL fails, it's up to procmail to deal with that.

# Code:

libdir=/usr/lib/cyrus-imapd
USER=${SUDO_USER-${USER-$LOGNAME}}

# Remove envelope from incoming message.
# Cyrus' lmtpd bombs if it sees a leading "From ".
sed -e '1{/^From /d;}' \
 | {
     if [ -g $libdir/deliver-wrapper ]; then
       case $# in
         0 ) set "user.$USER"    ;;
         1 ) set "user.$USER.$1" ;;
       esac

       $libdir/deliver-wrapper "$1"
     else
       case $# in
         0 ) $libdir/deliver -a "$USER" "$USER"         ;;
         * ) $libdir/deliver -a "$USER" -m "$1" "$USER" ;;
       esac
     fi
   }

# eof
