#!/bin/sh
# $Id$

chmod -R a+r,u+w,go-w ${1+"$@"}

if find --version > /dev/null 2>&1 ; then
  find ${1+"$@"} -type d -print0 \
   | xargs --null --no-run-if-empty chmod 2755
else
  find ${1+"$@"} -type d -print \
   | xargs chmod 2755
fi

# eof
