#!/bin/sh
# $Id: dvd2ipod,v 1.2 2010/04/15 08:49:56 friedman Exp $

exec HandBrakeCLI \
    --preset     "iPhone & iPod Touch" \
    --two-pass \
    --turbo \
    --markers \
    --ipod-atom \
    "$@"

# eof
