#!/bin/sh
# $Id: fix-directory-timestamps,v 1.4 2006/12/09 10:16:07 friedman Exp $

ignore='CVS RCS {arch} .svn'
ignore_meta='MD5SUM SHA1SUM TRANS.TBL'

case ${FDT_IGNOREMETA+set} in
  set ) ignore="$ignore $ignore_meta" ;;
esac

find_ign=`for i in $ignore; do echo ! -name $i ; done`
sed_ign=` for i in $ignore; do echo "/^$i\$/d" ; done`

find ${1+"$@"} $find_ign -type d -print \
  | sort -r \
  | while read d; do
     nfile=`ls -1At "$d" | sed -e "$sed_ign" -e q`
     case $nfile in
       '' ) : ;;
       * ) touch -r "$d/$nfile" "$d" ;;
     esac
   done

# eof
