#!/bin/sh
# $Id: fix-directory-timestamps,v 1.6 2006/12/28 22:00:30 friedman Exp $

ignore='CVS RCS {arch} .svn'
ignore_meta='MD5SUM SHA1SUM TRANS.TBL fonts.dir fonts.scale'

while :; do
  case $1 in
    -i ) ignore="$ignore $2"   ; shift ; shift ;;
    -m ) ignore="$ignore $ignore_meta" ; shift ;;
    *  ) break ;;
  esac
done

find_ign=`for i in $ignore; do echo ! -name $i ; done`
sed_ign=` for i in $ignore; do echo "/^$i\$/d" ; done`

find ${1+"$@"} $find_ign -type d -print \
  | sort -r \
  | while read d; do
     nfile=`ls -1At "$d" | sed -e "$sed_ign" -e q`
     case $nfile in
       '' ) : ;;
       * ) touch -r "$d/$nfile" "$d" ;;
     esac
   done

# eof
