#!/bin/sh
# $Id$

# A perhaps similar technique might be to use:
#   mencoder -oac copy -ovc lavc -o out.avi in.flv

for flv in ${1+"$@"}; do
  avi=`echo "$flv" | sed -e 's=.flv$=.avi='`
  ffmpeg -y -i "$flv" -acodec copy "$avi"
done

# eof
