#!/bin/sh
# $Id$

describe()
{
    openssl x509 -in "$1" -noout -text

    echo
    for type in md5 sha1; do
        openssl x509 -in "$1" -noout -fingerprint -$type
    done | sed -e 's/Fingerprint=//' | fmtcols -n2
}

fetch()
{
    h=`echo "$1" | sed -e 's=^[^:]*://==' -e 's=/.*=='`
    case $h in
        *:* ) : ;;
        * ) h=$h:443 ;;
    esac

    openssl s_client -connect $h < /dev/null 2>&0 |
        sed -ne '/^--*BEGIN /,/^--*END /p'
}

main()
{
    if [ -f "$1" ]; then
        describe "$1"
    else
        umask 022
        tmpfile=/tmp/get-ssl-cert.$$
        trap 'rm -f $tmpfile' 0 1 2 3 15
        fetch "$1" > $tmpfile
        cat $tmpfile
        echo
        describe $tmpfile
    fi
}

main "$@"

# eof
