#!/bin/sh
# $Id: gmplayer,v 1.1 2005/06/07 23:44:28 friedman Exp $

exec run-next "$0" \
    -quiet \
    -really-quiet \
    -nolirc \
    -nojoystick \
    -xy 2 \
    -loop 1024 \
    "$@" > /dev/null
