#! /bin/sh
# $Id: h2ph-inst,v 1.1 1998/03/19 23:35:18 friedman Exp $

depot=/tools/ns/soft
soft=perl-5.004_04

base_run=$depot/$soft/run/default
base_src=$depot/$soft/src
ludeclass=${LUDECLASS-`ludeclass`}

exec_prefix=$base_run/$ludeclass
prefix=$base_run/share

shbindir=$prefix/bin
bindir=$exec_prefix/bin

H2PH="$bindir/perl $shbindir/h2ph"
export H2PH

exec "$base_src/misc/h2ph-all" ${1+"$@"}

# h2ph-inst ends here
