#! /bin/sh
# $Id: h2ph-inst,v 1.2 1998/03/20 00:43:22 friedman Exp $

depot=/opt/lude/soft
soft=perl-5.005_03

base_run=$depot/$soft/run/private
ludeclass=${LUDECLASS-`ludeclass`}

exec_prefix=$base_run/$ludeclass
prefix=$base_run/share

shbindir=$prefix/bin
bindir=$exec_prefix/bin

H2PH="$bindir/perl $shbindir/h2ph"
export H2PH

exec "$shbindir/h2ph-all" ${1+"$@"}

# h2ph-inst ends here
