#!/usr/bin/env perl

push @ARGV, qw(/usr/share/dict/words) unless @ARGV;

my $prev = "";
while (<>)
  {
    next unless /^(?:[a-fios]{4}){1,4}$/i && /[aeoi]/i;
    y/iosIOS/105105/;
    print lc $_ if $_ ne $prev;
    $prev = $_;
  }
