#! /bin/sh
# kill-bad-cgi --- trivial script for killing wedged cgi processes
# Author: Noah Friedman <friedman@actlab.utexas.edu>
# Created: 1995-08-14
# Last modified: 1995-08-15
# Public domain

# Commentary:

# Usage: {-f} [signal]
# e.g.: "kill-bad-cgi -1" or "kill-bad-cgi -f -9"

# It should be safe to make this script setuid to `nobody' on Solaris 2.x.
# Other operating systems may not have fixed a security hole related to
# setuid shell scripts, so use this at your own risk.
# Be sure to edit the variable `user' below as appropriate.

# Code:

# Set these to secure values
PATH=/bin
IFS=" 	
"
export PATH IFS


case "$1" in
  -f ) force=t && shift ;;
  *  ) force=nil  ;;
esac

user=nobody
signal=${1--1}
found=nil

for pid in `ps -fu $user | sed -e 1d -e 's/ *[^ ]* *\([0-9]*\) .*/\1/'`
do
  if [ $pid -eq $$ ]; then continue; fi

  psinfo="`ps -fp $pid`"
  if [ $? -ne 0 ]; then continue; fi

  if [ $found = nil ]; then
    found=t
    echo "$psinfo"
  else
    echo "$psinfo" | sed -e 1d
  fi

  case $force in
    t )
      echo "*** kill $signal $pid"
      kill $signal $pid
     ;;
    * )
      echo "Kill process $pid (y/n)? \c"
      read ans
      case "$ans" in
        [Yy]* ) kill $signal $pid ;;
        * ) echo "Not killing $pid."
      esac
      echo
     ;;
  esac
done

if [ $found = nil ]; then
  echo "Nothing to kill."
else
  echo "Done."
fi

exit 0

# eof
