#!/bin/sh
# $Id: lic,v 1.2 2002/07/22 04:00:58 friedman Exp $

ls -la ${1+"$@"} \
  | perl -ane '$x = reverse $F[4];
               $x =~ s//$1,$2/o while ($x =~ /(\d{3})(\d)/o);
               $F[4] = reverse $x;
               print "@F\n";
              ' \
  | fmtcols --numeric-regexp '[\d:.]+' -Nwi '^total'
