#!/bin/sh
# $Id$

: ${SPHINXBUILD:=sphinx-build-3}

# Requires python3-sphinx (sphinx-build-3), or pip install Sphinx (sphinx-build)
if ! type $SPHINXBUILD > /dev/null 2>&1; then
    echo "Need python3-sphinx installed or pip install Sphinx." 1>&2
    exit 1
fi

case $# in
    0 ) { echo "Usage: ${0##*/} [version]"
          echo
          echo "e.g. \"${0##*/} 3.7.4\""
          echo
        } 1>&2
        exit 1 ;;
esac

ver=$1
tgz=v${ver}.tar.gz
url=https://github.com/python/cpython/archive/$tgz
dest=$HOME/lib/info/python/$ver

######
##
######

tmpdir=/var/tmp/python-doc$$
trap 'rm -rf $tmpdir' 0 1 2 3 15

set -e -x

mkdir -p $tmpdir

cd $tmpdir
# These flags keep from saving file to cpython-...tgz
# This way we get the exact file name we requested on disk
wget --no-trust-server-names --no-content-disposition $url
tar xf $tgz

cd cpython-$ver/Doc
$SPHINXBUILD -b texinfo -d build/doctrees . build/texinfo

cd build/texinfo && mmakeinfo python.texi

mkdir -p $dest
gzip -9v python.texi python.info
mv python.texi.gz python.info.gz $dest

# eof
