#!/bin/sh

: ${LC_CTYPE:=en_US.UTF-8}
export LC_CTYPE

args=(
    -hide_banner
    -loglevel		repeat+level+error

    -print_format	json
    -unit
    -prefix             -byte_binary_prefix
    -sexagesimal

    -show_format
    #-show_packets
    #-show_frames
    -show_streams
    -show_programs
    -show_chapters
    #-show_data            # show extradata in hex+ascii
    -show_private_data
    #-show_optional_fields always

    #-show_entries	'format      : streams     : programs     : chapters'
    #-show_entries	'format_tags : stream_tags : program_tags : chapter_tags'

    #-count_frames
    #-count_packets

    #-find_stream_info
)

exec ffprobe "${args[@]}" "$@"

# eof
