#!/bin/sh
# $Id$

do_tar()
{
    tar --create \
        --format=gnu \
        --quoting-style=escape \
        --owner=0 \
        --group=0 \
        --totals \
        --mode=644 \
        -b20 \
        -f "$@"
}

do_md5()
{
    md5sum -t "$1" >> "$1"
}

main()
{
    name=$1
    shift

    do_tar "$name" "$@" &&
    do_md5 "$name"      &&
    mv     "$name" "$name.md5"
}

main "$@"

# eof
