#!/usr/bin/env bash
# $Id: mkill,v 1.2 2010/02/22 10:53:00 friedman Exp $

fixup_pattern()
{
  arg=("$@")
  declare -i last=${#arg[@]}-1

  case ${arg[$last]} in
    *[][*^/]* ) : ;;
    *         ) arg[$last]="^([^ ]*/|)${arg[$last]}(\$| )" ;;
  esac
}

main()
{
  case ' '$*' ' in
    *' -v '* )
      exec 1>&2
      echo "The \`-v' flag doesn't do what you think it does.  Don't use it."
      exit 1 ;;
  esac

  signal=
  case $1 in
    -[0-9]* | -???* ) signal=$1 ; shift ;;
  esac

  uid=${UID-`id -u`}
  case $uid in
    0 ) : ;;
    * ) set fnord -u $uid "$@" ; shift ;;
  esac

  fixup_pattern "$@"
  set fnord "${arg[@]}"
  shift

  pgrep -fl "$@"
  pkill $signal -f "$@"
}

main "$@"

# eof
