#! /bin/sh
# $Id: mp3riplabel,v 1.2 1999/10/03 08:01:31 friedman Exp $

init ()
{
          ##############################
   album=''

          ##############################
  author=''

  year=
  genre=


  file_author=`acronymize "$author"`
  file_album=`acronymize "$album"`
}

acronymize ()
{
  case "$*" in
    *" "* | *-* )
      echo "$*" \
         | sed -e "s/^/ /" \
               -e "s/ *\([^ ]\)[^ ]*/\1/g" \
               -e "y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/"
     ;;
    * ) echo "$*" ;;
  esac
}

label ()
{
  file="track$1.cdda.mp3"
  title="$2"
  comment="$3"

  touch -r "$file" .stamp

  mp3info -W "$file"
  mp3info -t "$title" \
          -l "$album" \
          -a "$author" \
          -c "$comment" \
          -y "$year" \
          -g "$genre" \
    "$file"

  touch -r .stamp "$file"
  rm -f .stamp
}

rename ()
{
  old="track$1.cdda.mp3"
  title="$2"
  comment="$3"

  new=`echo "$title $comment" \
         | sed -e "s/  / /g" \
               -e "s/ $//" \
               -e "y/[(_ /----/" \
               -e "s/[]):.'!?]//g"`
  new="$file_author:$file_album-$1:$new.mp3"
  mv -v "$old" "$new"
}

doit ()
{
         ##############################   ##############################
  $1 01 "Example Title"                  "Example Comment"
}

init
doit label
doit rename

# eof
