#! /bin/sh
# $Id: p4-init-env,v 1.7 2000/05/26 05:10:16 friedman Exp $

# Commentary:

# Output proper p4 environment variable settings based on subnet.
# These should be eval'ed by the calling shell.

# Based 1999-10-15 on Ryan Hamilton's `p4set' tcsh script.

# Usage: eval `p4-init-env [user]`
#        eval `p4-init-env [-shell]`

# Code:

uid=`whoami`
user=${USER-${LOGNAME-$uid}}
hostname=${HOSTNAME-`hostname`}
hostname=`echo "$hostname" | sed 's/\..*//'`
shell=$SHELL

# Defaults which can be overridden below
case "${P4USER+set}" in
  set ) : ;;
  * )
    case "$1" in
      '' ) P4USER=$user ;;
      -* )
        P4USER=$user
        shell=`echo "x$1" | sed -e 's/^x-//'`
        shift
       ;;
      *  )
        P4USER=$1
        shift
       ;;
    esac
   ;;
esac

case "${P4CLIENT+set}" in
  set ) : ;;
  * )
    case "$hostname" in
      trabanten-schwein ) P4CLIENT=$uid.laptop    ;;
      puerco-del-diablo ) P4CLIENT=$uid.puerco    ;;
      * )                 P4CLIENT=$uid.$hostname ;;
    esac
   ;;
esac

case "${P4PORT+set}" in
  set ) : ;;
  * )
    # Determine subnet based on default route gateway
    subnet=`netstat -rn \
             | sed -n -e '/^default/b p' \
                      -e '/^0\.0\.0\.0/b p' \
                      -e d \
                      -e :p \
                      -e 's/[ 	][ 	]*/ /g' \
                      -e 's/^[^ ]* //' \
                      -e 's/ .*//' \
                      -e p -e q`

    case "$subnet" in
      192.168.1.* )         P4PORT=localhost ;; # prv.splode.com proxy

      # Production search clusters
      209.1.12.1 )          P4PORT=onyx      ;; # sc1-2
      209.185.141.1 )       P4PORT=jade      ;; # sc3
      64.75.36.1 )          P4PORT=hematite  ;; # sc4

      209.67.20[46].1 )     P4PORT=ruby      ;; # va1, va2
      205.188.182.253 \
      | 205.188.183.6[12] \
      | 205.188.184.254   ) P4PORT=sapphire  ;; # va3/4
      205.188.183.94 )      P4PORT=topaz     ;; # va5 admin
      205.188.183.254 )     P4PORT=sapphire  ;; # va5 SE nodes

      62.172.199.* )        P4PORT=beryl     ;; # uk1
      213.216.143.1 )       P4PORT=ivory     ;; # uk2

      216.35.11[678].1 )    P4PORT=feldspar  ;; # gigadoc
      209.185.122.1 )       P4PORT=amber     ;; # mini cluster
      209.202.174.161 )     P4PORT=cb-admin  ;; # cb2
      211.169.241.1 )       P4PORT=kyanite   ;; # kr1
      202.212.5.1 )         P4PORT=pearl     ;; # jp1
      210.172.228.129 )     P4PORT=lapis     ;; # jp2
      209.185.143.1 )       P4PORT=jade      ;; # j4k

      # Commerce nets; obsolete?
      64.41.217.1 )         P4PORT=diamond   ;; # congo
      64.75.7.1 )           P4PORT=dilithium ;; # sc4/2k commerce beta
      209.185.142.1 )       P4PORT=cryolite  ;; # congo
      213.216.144.1 )       P4PORT=erythrite ;; # uk/exodus shopping

      # Intranet
      209.131.48.1 )        P4PORT=quartz    ;; # internal, near quartz
      209.131.*.1 )         P4PORT=juniper   ;; # intranet
      * )                   P4PORT=jade      ;; # default
    esac

    # Append default tcp port if missing.
    case "$P4PORT" in
      *:* ) : ;;
      * ) P4PORT=$P4PORT:1666 ;;
    esac
   ;;
esac

# Emit the right syntax based on login shell.
case "$shell" in
  *[/-]* )
    shell=`echo "$shell" \
            | sed -e '/\//s=.*/==' \
                  -e '/-/s/-[^-]*$//'`
   ;;
esac

case "$shell" in
  csh | tcsh | zsh )
    echo "setenv P4PORT   $P4PORT;"
    echo "setenv P4USER   $P4USER;"
    echo "setenv P4CLIENT $P4CLIENT;"
   ;;
  emacs | scsh )
    progn="progn"
    case "$shell" in scsh ) progn="begin" ;; esac
    echo "($progn"
    echo "  (setenv \"P4PORT\"   \"$P4PORT\")"
    echo "  (setenv \"P4USER\"   \"$P4USER\")"
    echo "  (setenv \"P4CLIENT\" \"$P4CLIENT\"))"
   ;;
  * )
    echo "P4PORT=$P4PORT;"
    echo "P4USER=$P4USER;"
    echo "P4CLIENT=$P4CLIENT;"
    case "$shell" in
      es | rc ) : ;;
      * )
        echo "export P4PORT P4USER P4CLIENT;"
       ;;
    esac
  ;;
esac

# p4-init-env ends here.
