#!/bin/sh
# $Id$

# Is there some form of portable fd redirection trickery that would provide
# the equivalent of: a <(b) <(c)
# instead of needing to create temporary files?

fixes=${TMPDIR-/tmp}/unfixed-changes.fixes.$$
changes=${TMPDIR-/tmp}/unfixed-changes.changes.$$
cleanup() { e=$? ; rm -f "$fixes" "$changes" ; exit $e; }
trap cleanup 0 1 2 3 15

p4 fixes   ${1+"$@"} | awk '{print $5}' | sort -u > "$fixes"
p4 changes ${1+"$@"} | awk '{print $2}' | sort -u > "$changes"

comm -3 "$fixes" "$changes" | sed -e 's/^[ 	]*//' ;;

# eof
