#! /bin/sh
# $Id$

case $# in
  2 ) : ;;
  * )
    echo "Usage: phones2ps [infile.text] [outfile.ps]" 1>&2
    exit 1
  ;;
esac

perl -pe 's/\f/----------------------------------------/' "$1" \
 | pr -f -o 8 -h PHONES \
 | perl -p -e 's/^(\f?[ \t]+)([789][0-9]-)/\1\l19\2/;' \
           -e 's/   PHONES   /PHONES/;' \
 | enscript -B -DDuplex:true -M Letter -o "$2"
