#!/bin/sh
# $Id$

SNDDRV=${SNDDRV-alsa}
AUDIODEV=${AUDIODEV-default}

if [ -t 1 ]; then
  v_mpg123=-v
  v_sox=-S
  echo=echo
else
  v_mpg123=
  v_sox=-q
  echo=:
fi

for f in ${1+"$@"}; do
  $echo "$f"
  case $f in
    *.[Mm][Pp]3 | *.[Mm]4[Aa] ) ${MPG123-mpg123} -q $v_mpg123 -o $SNDDRV "$f" ;;
    *.wav | *.au | *.aiff     ) ${SOX-sox} $v_sox "$f" -t $SNDDRV $AUDIODEV ;;
    *                         ) ${PLAY-play} "$f" ;;
  esac
done

# eof
