#!/bin/sh

readmtime()
{
    awk -F' *:  *' \
        -e '/^ModDate:/ && $2 != "" { print $2; exit }' \
        -e '/^CreationDate:/ { tm=$2 }' \
        -e 'ENDFILE { print tm }'
}

for pdf in "$@"; do
    tm=`pdfinfo "$pdf" | readmtime`
    case $tm in
        '' ) tm="[no change                   ]" ;;
        *  ) touch -d "$tm" "$pdf"             ;;
    esac
    echo "[$tm]		$pdf"
done
