#!/bin/sh
# $Id: restore-pdf-mtime,v 1.1 2017/12/04 20:19:28 friedman Exp $

readmtime()
{
    awk -F' *:  *' \
        -e '/^ModDate:/ { print $2; exit }' \
        -e '/^CreationDate:/ { tm=$2 }' \
        -e 'ENDFILE { print tm }'
}

for pdf in "$@"; do
    tm=`pdfinfo "$pdf" | readmtime`
    case $tm in "" ) continue ;; esac
    touch -d "$tm" "$pdf"
done
