#!/bin/sh
# $Id: run-wine,v 1.1 2012/09/03 20:15:40 friedman Exp $

cd $HOME/etc/misc/.wine/dosdevices/c: || exit $?

prg=$1
shift

found=`find "Program Files"* -ipath "*/$prg" -o -ipath "*/$prg.exe"`
case $found in
    Program* ) prg=C:/$found ;;
esac

exec run-misc.sh ${WINE-wine} "$prg" "$@"

# eof
