#! /bin/sh
# $Id: run-netscape,v 1.2 1997/06/10 10:14:36 friedman Exp $

ver="$1"; shift
nam="$1"; shift

case "$ver" in
  '' | any ) : ;;
  *.* )
    MOZVERSION="$ver"
    export MOZVERSION
   ;;
  * )
    MOZMAJORVERSION="$ver"
    export MOZMAJORVERSION
   ;;
esac

case "$nam" in
  '' | normal ) : ;;
  * )
    MOZNAME="$nam"
    export MOZNAME
   ;;
esac

HOME=$HOME/etc/www/netscape
export HOME

case "$ver" in
  4* ) HOME="$HOME/dogbert" ;;
esac

exec netscape-fe ${1+"$@"}

# eof
