#! /bin/sh
# Run a specific version of a program, e.g. "run-version 19.27 emacs -fn 10x20"
# Author: Noah Friedman <friedman@cli.com>
# Created: 1995-07-10
# Public domain

# $Id$

progname=`echo "$0" | sed -e 's/[^\/]*\///g'`

case $# in
   0 )
     echo "usage: $progname [version] program ...." 1>&2
     exit 1
    ;;
esac

sed_foldcase='y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'

ver=`echo "$1" | sed -e "$sed_foldcase"`
shift

prog=`echo "$1" | sed -e 's/[^\/]*\///g' -e "$sed_foldcase"`

eval ${prog}VERSION=$ver
eval export ${prog}VERSION

exec ${1+"$@"}

# run-version ends here
