#! /bin/sh
# $Id: run-netscape,v 1.6 1999/05/25 04:41:35 friedman Exp $

case "$1" in
  -* ) ;;
  * )
    ver="$1"; shift
    nam="$1"; shift

    case "$ver" in
      '' | any ) : ;;
      *.* )
        MOZVERSION="$ver"
        export MOZVERSION
       ;;
      * )
        MOZMAJORVERSION="$ver"
        export MOZMAJORVERSION
       ;;
    esac

    case "$nam" in
      '' | normal ) : ;;
      * )
        MOZNAME="$nam"
        MOZPROG="$nam"
        export MOZNAME MOZPROG
       ;;
    esac
   ;;
esac

HOME=$HOME/etc/www/netscape
export HOME

prefs=$HOME/.netscape/preferences.js
if ls -d $HOME/.netscape/lock 2> /dev/null; then
  :
elif [ -f "${prefs}.append" ] && [ -f "$prefs" ]; then
  cat "${prefs}.append" >> "$prefs"
fi

exec netscape-fe ${1+"$@"}

# eof
