#!/bin/sh
# sendemacs
# Author: Roland McGrath <roland@prep.ai.mit.edu>
# Date: 1994-10-24

# $Id$

# Commentary:

# What made me feel this sudden need was the support that sort of works
# in the last day or two in the Emacs development sources for multiple X
# displays.  This inspired me just now to write this little ditty I call
# ~/bin/sendemacs, which works nicely.

# Code:

test -n "$DISPLAY" && { set dummy -display "$DISPLAY" "$@"; shift; }

args="'("
while [ $# -gt 0 ]; do
  arg=`echo "$1" | sed 's/"/\\"/g'`
  args="$args \"${arg}\""
  shift
done
args="$args)"

emacsdo <<EOF

(condition-case loser
    (mapcar 'find-file
	    (let (default-frame-alist initial-frame-alist
		   x-display-name x-resource-name
		   x-command-line-resources)
	      (prog1 (x-handle-args $args)
		(or (member x-display-name (x-display-list))
		    (x-open-connection x-display-name
				       x-command-line-resources
				       nil))
		(x-create-frame (cons (cons 'display x-display-name)
				      (nconc (and x-resource-name
						  (cons 'resource-name
							x-resource-name))
					     initial-frame-alist
					     default-frame-alist))))))
  (error (message "sendemacs: %s" loser) (feep t))
  (quit nil))

EOF

# sendemacs ends here
