#!/bin/sh
# $Id$

case "$HOME" in
  /u/$USER | /home/$USER ) HOME=$HOME/etc/soffice ;;
esac

if [ -d $HOME/adabas ]; then
  DBROOT=$HOME/adabas
  DBWORK=$DBROOT/sql
  DBCONFIG=$DBROOT/sql
  PATH=$DBROOT/bin:$DBROOT/pgm:$PATH
  LD_LIBRARY_PATH=$DBROOT/lib${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}
  export DBROOT DBWORK DBCONFIG PATH LD_LIBRARY_PATH
fi

case "$1" in
  --run )
    shift
    exec ${1+"$@"}
   ;;
  * )
    exec $HOME/office52/soffice ${1+"$@"}
   ;;
esac
