#!/bin/sh
# $Id: soffice,v 1.2 2003/07/12 19:50:02 friedman Exp $

case "$HOME" in
  /u/$USER | /home/$USER ) HOME=$HOME/etc/misc ;;
esac

if [ -d $HOME/adabas ]; then
  DBROOT=$HOME/adabas
  DBWORK=$DBROOT/sql
  DBCONFIG=$DBROOT/sql
  PATH=$DBROOT/bin:$DBROOT/pgm:$PATH
  LD_LIBRARY_PATH=$DBROOT/lib${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}
  export DBROOT DBWORK DBCONFIG PATH LD_LIBRARY_PATH
fi

case $1 in
  --run )
    shift
    exec "$@"
   ;;
  * )
    exec $HOME/.openoffice/soffice "$@"
   ;;
esac
