#!/usr/bin/env bash

: ${SQLITE:=sqlite3}

declare db
declare -a sqlite_flags=(
    -readonly
    -cmd '.timeout 100' # msec

    -header
    -nullvalue NULL

    -list
    -separator ' | '

    #-box
)

apush() { eval "$1=(\"\${$1[@]}\" \"\${@:2}\")"; }

find_db()
{
    if [ -f "$db" ]; then
        return
    elif [ -f "$db.sqlite" ]; then
        db=$db.sqlite
    elif [ -f "$db.db" ]; then
        db=$db.db
    else
        echo "$db: database not found" 1>&2
        exit 1
    fi
}

main()
{
    while [[ $# -gt 2 ]] || [[ ${1:0:1} = '-' ]] ; do
        case $1 in
            /* | *.sqlite | *.db ) break ;;
        esac
        test -f "$1" && break

        apush sqlite_flags "$1"
        shift
    done

    db=$1
    shift
    find_db

    case ${1,,} in
        select* ) : ;;
        * ) set "SELECT" "$@" ;;
    esac

    $SQLITE "${sqlite_flags[@]}" "$db" "$*"
}

main "$@"

# eof
