#!/bin/sh
# $Id: touch-epoch,v 1.4 1997/03/28 09:17:12 friedman Exp $

TZ=GMT
export TZ

if touch --version > /dev/null 2>&1 ; then
  exec touch -d 'Jan 01, 1970 00:00' ${1+"$@"}
else
  exec perl -e '
    foreach $file (@ARGV)
      {
        @statinfo = stat ($file);
        utime ($statinfo[8], 0, $file);
      }' -- ${1+"$@"}
fi

# touch-epoch ends here
