#!/bin/sh
# $Id$

tightvnc()
{
  encodings='copyrect tight hextile zlib corre rre'
  with -N run-misc.sh "$0" -encodings "$encodings" "$@"
}

realvnc()
{
  with -N run-misc.sh "$0" -AlwaysShared -Shared "$@"
}

main()
{
  vncviewer=`run-next -p "$0"`
  vncversion=`$vncviewer --version 2>&1`

  case $vncversion in
    TightVNC*       ) tightvnc "$@" ;;
    *"RealVNC Ltd"* ) realvnc  "$@" ;;
  esac
}

main "$@"

# eof
