#!/bin/sh
# $Id: vncviewer,v 1.2 2009/10/01 23:34:44 friedman Exp $

# Note: OSX RDP is busted and only recognizes hextile encoding.
# For realvnc, use:  -FullColor -PreferredEncoding hextile

tigervnc()
{
  with -N run-misc.sh "$0" -Shared "$@"
}

realvnc()
{
  with -N run-misc.sh "$0" -AlwaysShared -Shared "$@"
}

tightvnc()
{
  encodings='copyrect tight hextile zlib corre rre'
  with -N run-misc.sh "$0" -encodings "$encodings" "$@"
}

main()
{
  vncviewer=`run-next -p "$0"`
  vncversion=`$vncviewer --version 2>&1`

  case $vncversion in
    *TigerVNC*      ) tigervnc "$@" ;;
    *"RealVNC Ltd"* ) realvnc  "$@" ;;
    *TightVNC*      ) tightvnc "$@" ;;
  esac
}

main "$@"

# eof
