#!/bin/sh
# $Id$

ffm()
{
  local in=$1
  local out=$2
  shift 2

  ffmpeg -i "$in" \
      -f avi \
      -deinterlace \
      -vcodec mpeg4 \
      -b 1500k \
      -g 300 \
      -bf 2 \
      -vtag DIVX \
      -acodec mp3 \
      -ab 128 \
      "$@" "$out"
}

for vob in ${1+"$@"}; do
  avi=`basename "$vob" | sed -e 's=.[Vv][Oo][Bb]$=.avi='`

  rm -f ffmpeg2pass-0.log ",pass1.$avi"
  ffm "$vob" ",pass1.$avi" -pass 1
  ffm "$vob" "$avi" -pass 2
done
