#! /bin/sh
# $Id: whois,v 1.1 1999/08/25 22:15:40 friedman Exp $

if { jwhois --version } > /dev/null 2>&1 ; then
  whois="jwhois"
else
  whois=`run-next -p "$0"`
fi

"$whois" ${1+"$@"} \
 | perl -e '
     $/ = undef;
     $buf = <>;
     @s = ("The Data in Network Solutions.*abide by this policy.\n+",
           ".*www.nic.fr/info/whois/dbcopyright.html\n+",
           "The ARIN Registration Services Host.*NIPRNET Information.\n+",
          );
     foreach $r (@s) { if ($buf =~ /$r/s) { $buf =~ s/$r//s; last; } }
     print $buf;
   '
