#! /bin/sh

# $Id$

HOME="$1"
export HOME

shift

if test -d "$HOME" || mkdir "$HOME" ; then
  exec ${1+"$@"}
else
  echo "Directory \`$HOME' does not exist and could not create." 1>&2
  exit 1
fi

# eof
