#! /bin/sh
# $Id: xauth-copy,v 1.1 2007/07/04 02:35:43 friedman Exp $

key=$1
from=$2
to=$3

case $# in
  1 ) from=$HOME/.Xauthority
        to=$HOME/etc/misc/.Xauthority ;;
esac

xauth -f "$from" extract - "$key" | xauth -f "$to" merge -
