#!/bin/sh
# $Id$

case $1 in
  on )  cmd=-a ;;
  off ) cmd=-d ;;
  * ) echo "Usage: xutmp [on|off]" 1>&2; exit 1 ;;
esac

tty=`tty 2> /dev/null | sed -e 's=^/dev/=='`
case $tty in
  'not a tty' ) tty=`readlink /proc/self/fd/0 | sed -e 's/[][]//g'` ;;
esac

exec sessreg $cmd -w none -l "$tty" -h "$DISPLAY" "$USER"

# eof
